AWSTemplateFormatVersion: 2010-09-09

Description: This stack creates a EC2 Instance.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  KeyPair:
    Description: "Name of an existing EC2 KeyPair to enable SSH/RDP access to the instance"
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: "must be the name of an existing EC2 KeyPair."
  EC2InstanceSize:
    Description: "Size of the EC2 instance"
    Type: String
    Default: "t2.micro"
  EC2ImageId:
    Description: "ImageId of the EC2 Instance in this Region"
    Type: String
    Default: "ami-0e9089763828757e1"

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: !Ref EC2ImageId
      InstanceType: !Ref EC2InstanceSize
      Monitoring: false
      SubnetId: !ImportValue ref-public-subnet-az1-id
      SecurityGroupIds:
        - !ImportValue ref-security-group-id
      IamInstanceProfile: !ImportValue ref-ec2s3-instance-profile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-1.8*
          update-alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
          java -version
          wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
          yum install -y jenkins
          service jenkins start
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-jenkins-server
        - Key: Project
          Value: !Sub ${EnvironmentName}

  Inbound8080Rule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !ImportValue ref-security-group-id
      IpProtocol: tcp
      FromPort: "8080"
      ToPort: "8080"
      CidrIp: !ImportValue ref-security-group-ingress-cidr
      Description: "Allow ingress on port 8080"

Outputs:
  JenkinsServer:
    Description: public IP address of EC2 instance
    Value: !GetAtt JenkinsServer.PublicIp
