version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'target/ccdemo.war' # This will create a folder called target and put the war file in.
    - 'appspec.yml'
    - 'scripts/before_install.sh' 
    - 'scripts/after_install.sh'    
    - 'scripts/start_server.sh'
    - 'scripts/stop_server.sh'    
    # this will create a folder called scripts and put all the scripts in. the zip file will content the appspec, the war and all the scripts needed to run deploy the application.