AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: AWS::EC2::KeyPair::KeyName
    Default: cfn-key-1
    AllowedValues: 
      - cfn-key-1
      - cfn-key-2
      
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0cd3dfa4e37921605
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default        
        - !Ref SSHSecurityGroup 
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0