# This role will allow CodeBuild to access S3 and put artifact, pull code from CodeCommit and put logs in cloudwatch.

Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        Fn::Sub: CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: "CodeBuildCICDAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "codecommit:GitPull"
                Resource:
                  - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${ApplicationRepoName}
                  # "arn:aws:codecommit:us-east-2:788210522308:ccdemo"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                  # "arn:aws:logs:us-east-2:788210522308:log-group:/aws/codebuild/ccdemo2"
                  # "arn:aws:logs:us-east-2:788210522308:log-group:/aws/codebuild/*"
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn:aws:s3:::codepipeline-${AWS::Region}-*
                  # "arn:aws:s3:::codepipeline-us-east-2-*"
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}/* 
                  # "arn:aws:s3:::artifact-tia/*"
                  - Fn::Sub: arn:aws:s3:::${ArtifactStoreS3Location}
                  # "arn:aws:s3:::artifact-tia"

