AWSTemplateFormatVersion: 2010-09-09
Resources:
  myec2Instance:
    Type: "AWS::EC2::Instance"
    Metadata:
      "AWS::CloudFormation::Init":
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: !Join ["", ["This is created by cfn-init"]]
              mode: "000644"
              owner: root
              group: root
          commands:
            StratApache:
              command: service httpd start
    Properties:
      KeyName: sampleapp-linux-key-pair
      ImageId: ami-0e9089763828757e1
      SecurityGroupIds:
        - sg-0a4222fede8d67e41
      InstanceType: t2.micro
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource myec2Instance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource myec2Instance --region ${AWS::Region}
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
