AWSTemplateFormatVersion: 2010-09-09
Description: Using intrinsic Funstions and parameters
Parameters:
  s3NamePrefix:
    Description: Enter the unique prefix to the name of the S3 bucket you need to create
    Type: String
    Default: mybucket
  DBPassword:
    Description: DB Password
    Type: String
    NoEcho: true
    MinLength: 1
    MaxLength: 8
    AllowedPattern: ^[a-zA-Z0-9]*$
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small or m1.large
Resources:
  s3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join [
          "-",
          [!Ref s3NamePrefix, !Ref "AWS::StackName", !Ref "AWS::Region"],
        ]
