AWSTemplateFormatVersion: 2010-09-09
Description: Test Custom resource
Parameters:
  GroupDescription:
    Type: String
    Default: Enter data to be passed
Resources:
  createSg:
    Type: "AWS::CloudFormation::CustomResource"
    Version: "1.0"
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:404522240888:function:CustomResource
      GroupDescription: !Ref GroupDescription
